from __future__ import annotations

import argparse
import copy
import os
from pathlib import Path
import platform
import sys

import numpy as np
import pytorch_lightning as pl
import torch
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint, LearningRateMonitor
from pytorch_lightning.loggers import CSVLogger, TensorBoardLogger

from src.config import load_config, project_path, config_hash, validate_config
from src.data.filters import load_filters
from src.dataset import MixData_Module
from src.factory import make_kernels, make_model, make_datamodule
from src.components import build_component
from src.utils import atomic_json, atomic_yaml, file_hash, load_checkpoint, source_tree_hash


def train(config: dict):
    validate_config(config)
    pl.seed_everything(config["seed"], workers=True)
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
    torch.set_float32_matmul_precision("highest")
    data = dict(config["data"])
    data_dir = project_path(data["data_dir"])
    run_dir = project_path(config["run"]["output_dir"]) / config["run"]["name"]
    resume = config["run"]["resume"]
    if resume is None and run_dir.exists() and any(run_dir.iterdir()):
        raise FileExistsError(f"Run directory already exists: {run_dir}. Use a new run.name or --resume.")
    run_dir.mkdir(parents=True, exist_ok=True)
    dm = make_datamodule(config)
    dm.setup("fit")
    ds = dm.train_dataset
    filters_path = project_path(data["filters"]) if data["filters"] else data_dir / "filters.npz"
    filters = load_filters(filters_path)
    if ds.n_fft < ds.source_length + max(map(len, filters)) - 1:
        raise ValueError("n_fft truncates the full linear convolution")
    kernels = make_kernels(filters, ds.n_fft)
    metadata = dict(n_fft=ds.n_fft, source_length=ds.source_length, num_sources=ds.num_sources,
                    sample_rate=ds.sample_rate, fft_norm=ds.fft_norm,
                    filters_sha256=file_hash(filters_path), train_sha256=file_hash(ds.path),
                    cv_sha256=file_hash(dm.val_dataset.path))
    model = make_model(config, n_fft=ds.n_fft, kernels=kernels)
    model.data_metadata = metadata
    ckpt_path = None
    if resume is not None:
        ckpt_path = project_path(resume)
        old = load_checkpoint(ckpt_path, trust=config["run"]["trust_checkpoint"])
        previous = old.get("convmix", {})
        if previous.get("config") is None:
            raise ValueError("Resume requires a checkpoint generated by this packaged workflow")
        if previous["config"]["seed"] != config["seed"]:
            raise ValueError("Cannot change the training seed on resume")
        for key in ("batch_size", "drop_last", "train_subset"):
            if previous["config"]["data"][key] != config["data"][key]:
                raise ValueError(f"Cannot change data.{key} on resume")
        for section in ("sde", "network", "model"):
            if previous["config"][section] != config[section]:
                raise ValueError(f"Cannot silently change {section} while resuming")
        protected_components = ("model", "sde", "score_model", "loss", "optimizer", "scheduler",
                                "time_sampler", "validation_time_sampler", "noise_sampler", "ema_update", "loss_selection")
        for name in protected_components:
            if previous["config"].get("components", {}).get(name) != config.get("components", {}).get(name):
                raise ValueError(f"Cannot change component {name} while resuming")
        if previous.get("metadata") != metadata:
            raise ValueError("Dataset/filter metadata differ from the resumed run")
        if config["trainer"]["max_epochs"] <= int(old.get("epoch", -1)) + 1:
            raise ValueError("max_epochs is not greater than the completed checkpoint epoch count")
    atomic_yaml(run_dir / "resolved.yaml", config)
    atomic_json(run_dir / "manifest.json", {"config_hash": config_hash(config), "metadata": metadata, "source_tree_sha256": source_tree_hash()})
    atomic_json(run_dir / "environment.json", {"python": sys.version, "platform": platform.platform(),
        "torch": str(torch.__version__), "lightning": pl.__version__, "numpy": np.__version__,
        "cuda_available": torch.cuda.is_available(), "cuda_version": torch.version.cuda})
    # Preserve old metrics on resume: CSVLogger would otherwise overwrite them.
    from datetime import datetime, timezone
    session = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S_%fZ")
    csv_version = "" if resume is None else "resume_" + session
    atomic_yaml(run_dir / "sessions" / (session + ".yaml"), config)
    tc = dict(config["trainer"])
    patience, top_k = tc.pop("early_stopping_patience"), tc.pop("save_top_k")
    components = config.get("components", {})
    if components:
        loggers = []
        for name, spec in components["logger"].items():
            if spec is None:
                continue
            kwargs = {"save_dir": str(run_dir)} if name in ("csv", "tensorboard") else {}
            if name == "csv":
                kwargs["version"] = csv_version
            loggers.append(build_component(spec, **kwargs))
        callbacks = []
        for name, spec in components["callbacks"].items():
            if spec is not None:
                kwargs = {"dirpath": str(run_dir / "checkpoints")} if name == "checkpoint" else {}
                callbacks.append(build_component(spec, **kwargs))
        checkpoint = next((c for c in callbacks if isinstance(c, ModelCheckpoint)), None)
        if checkpoint is None:
            raise ValueError("A ModelCheckpoint-compatible callback is required by this workflow")
        trainer = build_component(components["trainer"], **tc, callbacks=callbacks,
                                  logger=loggers or False, default_root_dir=str(run_dir))
    else:
        loggers = [CSVLogger(str(run_dir), name="csv", version=csv_version)]
        if config["run"]["tensorboard"]:
            loggers.append(TensorBoardLogger(str(run_dir), name="tb", version=""))
        checkpoint = ModelCheckpoint(dirpath=run_dir / "checkpoints", filename="epoch={epoch:04d}",
            monitor="val/score_loss", mode="min", save_top_k=top_k, save_last=True,
            auto_insert_metric_name=False)
        callbacks = [checkpoint, LearningRateMonitor(logging_interval="epoch")]
        if patience > 0:
            callbacks.append(EarlyStopping("val/score_loss", mode="min", patience=patience))
        trainer = pl.Trainer(**tc, callbacks=callbacks, logger=loggers, default_root_dir=run_dir)
    (run_dir / "model_structure.txt").write_text(str(model.score_model))
    if "hydra_config" in config:
        atomic_yaml(run_dir / "hydra_config.yaml", config["hydra_config"])
    if components:
        atomic_json(run_dir / "components.json", components)
    print(f"Run directory: {run_dir}\nK={ds.num_sources}, n_fft={ds.n_fft}; structured SDE enabled", flush=True)
    # Explicitly pass weights_only so Lightning does not change the trust policy.
    # Older supported Lightning versions omit this argument; safe loading above
    # has already checked the file but Trainer may still need trusted metadata.
    import inspect
    fit_kwargs = {}
    if "weights_only" in inspect.signature(trainer.fit).parameters:
        fit_kwargs["weights_only"] = not config["run"]["trust_checkpoint"]
    trainer.fit(model, datamodule=dm, ckpt_path=str(ckpt_path) if ckpt_path else None, **fit_kwargs)
    artifact = {"best": checkpoint.best_model_path, "last": checkpoint.last_model_path,
                "global_step": trainer.global_step, "completed_epochs": int(trainer.current_epoch),
                "ema_updates": int(model.ema_updates), "config_hash": config_hash(config)}
    atomic_json(run_dir / "artifacts.json", artifact)
    print("Training artifacts:", artifact, flush=True)
    return run_dir


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/experiments/mechanical_k2.yaml")
    parser.add_argument("--set", nargs="*", default=[], metavar="KEY=VALUE")
    parser.add_argument("--resume", default=None)
    parser.add_argument("--trust-checkpoint", action="store_true")
    args = parser.parse_args()
    cfg = load_config(args.config, args.set)
    if args.resume is not None:
        cfg["run"]["resume"] = args.resume
    if args.trust_checkpoint:
        cfg["run"]["trust_checkpoint"] = True
    train(cfg)


if __name__ == "__main__":
    main()
